query{
    products(sort:price){
        _id
        title
        description
        price
        category(count:3){
            _id
            name
        }
    }
}
mutation{
    addCategory{
        name
    }
}
